### ISSUE TITLE
box contains funtion

### ISSUE THREAD

**Issue by amazingluyk** [pvigier/Quadtree#10]
constexpr bool contains(const Box<T>& box) const noexcept
    {
        return left <= box.left && box.getRight() <= getRight() &&
            **top <= box.top** && box.getBottom() <= getBottom();
    }

I think it should be 

    constexpr bool contains(const Box<T>& box) const noexcept
    {
        return left <= box.left && box.getRight() <= getRight() &&
            **top >= box.top** && box.getBottom() <= getBottom();
    }

**Comment by amazingluyk** [comment]
sorry, u are right

**Comment by cwsmith** [comment]
I got tripped up on the same thing and it seems like 'top' should really be named 'bottom'.  Some digging on this is below.  

getBottom in Box.h is defined:

https://github.com/pvigier/Quadtree/blob/d205190a5e74527746acaade89309b33b00985c6/include/Box.h#L34-L37

Given that, if I want a box with min = 0,0 and max = 20, 20, it seems like I would need to create the Box object with {left=0, top=20, width=20, height=-20}?  But this comment in Box.h indicates that height must be positive:

https://github.com/pvigier/Quadtree/blob/d205190a5e74527746acaade89309b33b00985c6/include/Box.h#L15

So, that gives me a Box ctor call {left=0, top=0, width=20, height=20} ... which seems to match the convention of the unit square being used in tests and examples:

https://github.com/pvigier/Quadtree/blob/d205190a5e74527746acaade89309b33b00985c6/tests/tests.cpp#L114

**Comment by pvigier** [comment]
In 2D graphics programming, it is very common that the Y-axis is oriented down (top left of your screen is (0, 0), bottom right is (width, height)). It is the case here. This may confuse you if you come from a maths background.

**Comment by cwsmith** [comment]
Ahhhh.  Thank you. 👍
