### ISSUE TITLE
Is this can be used to detect a set of line segment intersect ?

### ISSUE THREAD

**Issue by jincongcong** [pvigier/Quadtree#3]

**Comment by pvigier** [comment]
Yes, you can insert in the quadtree the smallest boxes containing the line segments (easily computed using the endpoints, you may have to be careful with horizontal and vertical line segments which will have 0 width or 0 height bounding boxes, you may have to change some inequalities for strict inequalities or the other way around). Then, you find intersections between the boxes to find the potential line segment intersections. Finally, for each box intersection, you check if the corresponding line segments are really intersecting.
