### ISSUE TITLE
Documentation lacks dependencies

### ISSUE THREAD

**Issue by denizetkar** [pvigier/Quadtree#7]
Hi Pierre,

Thank you for providing such a well packaged implementation of quadtrees. However, I would like to kindly ask you to include dependencies of the project in the readme file, in order to get it running quickly in a linux machine. I personally had to spend a few hours figuring out how to build your project using cmake, because of some dependencies which I was not aware of and then didn't know how to easily install them. To be specific, I'm working on an Ubuntu 20 machine with x64 CPU and the dependencies I had to install were Google Benchmark and Google Test C++ libraries using **apt** package manager:
```bash
sudo apt install libbenchmark-dev libgtest-dev
```

So far these are the dependencies I discovered and should there be more, please let us know :)

**Comment by pvigier** [comment]
Hi,

CMake should emit error messages that tell which libraries are missing. But I will add a line in the README to be sure.

I will also disable building the benchmarks and tests by default. This way, no dependencies would be required for the default case.
