### ISSUE TITLE
Wrong float in quadtree constructor?

### ISSUE THREAD

**Issue by beurnii** [pvigier/Quadtree#8]
Hi,

I am trying to make a unsigned int quadtree. In the template, I put unsigned in the last parameter. Everywhere is the code it uses the "Float" type except a single place in the constructor (Quadtree.h Line:24)

Was that intended? Is it even possible to do a unsigned quadtree?

Thanks!
Beurnii

**Comment by pvigier** [comment]
Hi,
I used a template parameter `Float` to be able to use the quadtree with `float`, `double` or any other floating point type.

The code isn't intended to work with integer types. There may be issues with the division by 2 here:
https://github.com/pvigier/Quadtree/blob/a28cb41eeee3f020eb807cf9d7fd5859f62bbacd/include/Quadtree.h#L78
And maybe at other places. It is maybe possible to adapt the code to work with integer types with only slight modifications.

**Comment by beurnii** [comment]
Alright thanks for the info. I'll use it with floats. Thanks for your work!
